/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    CircularProgress: typeof import('./src/components/CircularProgress.vue')['default']
    ConfirmModal: typeof import('./src/components/shared/ConfirmModal.vue')['default']
    ConnectionDetailPanel: typeof import('./src/components/connections/ConnectionDetailPanel.vue')['default']
    ConnectionListItem: typeof import('./src/components/connections/ConnectionListItem.vue')['default']
    ConnectionsSidebar: typeof import('./src/components/connections/ConnectionsSidebar.vue')['default']
    ConnectionsWorkspace: typeof import('./src/components/connections/ConnectionsWorkspace.vue')['default']
    MainToolbar: typeof import('./src/components/MainToolbar.vue')['default']
    PrerequisitesFooter: typeof import('./src/components/PrerequisitesFooter.vue')['default']
    ProfileFormModal: typeof import('./src/components/profiles/ProfileFormModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    StatusBadge: typeof import('./src/components/shared/StatusBadge.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    TunnelNotifier: typeof import('./src/components/tunnels/TunnelNotifier.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
  }
}
