// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckLocalPort(arg1:number):Promise<models.PortStatus>;

export function CheckPrerequisites():Promise<models.Prerequisites>;

export function DeleteFavorite(arg1:string):Promise<void>;

export function ExportFavorites():Promise<string>;

export function GetAwsAuthMethod(arg1:string):Promise<string>;

export function GetAwsDefaults():Promise<models.AWSDefaults>;

export function HideToTray():Promise<void>;

export function ImportFavorites():Promise<models.ImportResult>;

export function ListActiveTunnels():Promise<Array<models.Tunnel>>;

export function ListAwsProfiles():Promise<Array<string>>;

export function ListAwsRegions():Promise<Array<string>>;

export function ListFavorites():Promise<Array<models.Favorite>>;

export function ListManagedInstances(arg1:string,arg2:string):Promise<Array<models.Instance>>;

export function OpenAwsInstallDocs():Promise<void>;

export function PickPrivateKeyFile():Promise<string>;

export function SaveFavorite(arg1:models.Favorite):Promise<models.Favorite>;

export function StartTunnel(arg1:string):Promise<models.Tunnel>;

export function StopTunnel(arg1:string):Promise<void>;
