// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLocalPort(arg1) {
  return window['go']['main']['App']['CheckLocalPort'](arg1);
}

export function CheckPrerequisites() {
  return window['go']['main']['App']['CheckPrerequisites']();
}

export function DeleteFavorite(arg1) {
  return window['go']['main']['App']['DeleteFavorite'](arg1);
}

export function ExportFavorites() {
  return window['go']['main']['App']['ExportFavorites']();
}

export function GetAwsAuthMethod(arg1) {
  return window['go']['main']['App']['GetAwsAuthMethod'](arg1);
}

export function GetAwsDefaults() {
  return window['go']['main']['App']['GetAwsDefaults']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function ImportFavorites() {
  return window['go']['main']['App']['ImportFavorites']();
}

export function ListActiveTunnels() {
  return window['go']['main']['App']['ListActiveTunnels']();
}

export function ListAwsProfiles() {
  return window['go']['main']['App']['ListAwsProfiles']();
}

export function ListAwsRegions() {
  return window['go']['main']['App']['ListAwsRegions']();
}

export function ListFavorites() {
  return window['go']['main']['App']['ListFavorites']();
}

export function ListManagedInstances(arg1, arg2) {
  return window['go']['main']['App']['ListManagedInstances'](arg1, arg2);
}

export function OpenAwsInstallDocs() {
  return window['go']['main']['App']['OpenAwsInstallDocs']();
}

export function PickPrivateKeyFile() {
  return window['go']['main']['App']['PickPrivateKeyFile']();
}

export function SaveFavorite(arg1) {
  return window['go']['main']['App']['SaveFavorite'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}
